apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kafka-manage.fullname" . }}
  labels:
    {{- include "kafka-manage.labels" . | nindent 4 }}
data:
{{- if .Values.state }}
{{ $root := . }}
  {{- range $key, $value := .Values.state }}
  {{ $key }}: |
{{ tpl (toYaml $value | indent 4) $root }}
  {{- end -}}
{{- end -}}

{{- if .Values.notifiers }}
  {{- range $key, $value := .Values.notifiers }}
  {{ $key }}: |
{{ toYaml $value | indent 4 }}
  {{- end -}}
{{- end -}}
